//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POM.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlotsOnMapsDBEntities4 : DbContext
    {
        public PlotsOnMapsDBEntities4()
            : base("name=PlotsOnMapsDBEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARTICULO> ARTICULO { get; set; }
        public virtual DbSet<CONJUNTO_ARTICULOS> CONJUNTO_ARTICULOS { get; set; }
        public virtual DbSet<CONJUNTO_PARCELAS> CONJUNTO_PARCELAS { get; set; }
        public virtual DbSet<COORDENADAS_OPERACION> COORDENADAS_OPERACION { get; set; }
        public virtual DbSet<COORDENADAS_PARCELA> COORDENADAS_PARCELA { get; set; }
        public virtual DbSet<FINCA> FINCA { get; set; }
        public virtual DbSet<OPERACION> OPERACION { get; set; }
        public virtual DbSet<PARCELA> PARCELA { get; set; }
        public virtual DbSet<TIPO_OPERACION> TIPO_OPERACION { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<VARIEDAD> VARIEDAD { get; set; }
        public virtual DbSet<lstvariedades> lstvariedades { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
