//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POM.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPERACION()
        {
            this.CONJUNTO_ARTICULOS = new HashSet<CONJUNTO_ARTICULOS>();
            this.CONJUNTO_PARCELAS = new HashSet<CONJUNTO_PARCELAS>();
            this.COORDENADAS_OPERACION = new HashSet<COORDENADAS_OPERACION>();
        }
    
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string COLOR { get; set; }
        public string TIPO { get; set; }
        public string FECHA { get; set; }
        public string FECHA2 { get; set; }
        public string ARTICULOS { get; set; }
        public string OBSERVACIONES { get; set; }
        public int TROZOS { get; set; }
        public string PARCELA { get; set; }
        public string FINCA { get; set; }
        public string USUARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONJUNTO_ARTICULOS> CONJUNTO_ARTICULOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONJUNTO_PARCELAS> CONJUNTO_PARCELAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COORDENADAS_OPERACION> COORDENADAS_OPERACION { get; set; }
        public virtual TIPO_OPERACION TIPO_OPERACION { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
