//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POM.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARCELA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARCELA()
        {
            this.CONJUNTO_PARCELAS = new HashSet<CONJUNTO_PARCELAS>();
            this.COORDENADAS_PARCELA = new HashSet<COORDENADAS_PARCELA>();
        }
    
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string CONJUNTA { get; set; }
        public string VARIEDAD { get; set; }
        public string FINCA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONJUNTO_PARCELAS> CONJUNTO_PARCELAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COORDENADAS_PARCELA> COORDENADAS_PARCELA { get; set; }
        public virtual FINCA FINCA1 { get; set; }
        public virtual VARIEDAD VARIEDAD1 { get; set; }
    }
}
